In [1]:
import numpy as np

In [2]:
def seq(start, end=None, step=1):
    if isinstance(start, list):
        end = len(start)
        start = 0
    if end == None:
        end = start
        start = 0
    _seq = []
    length = int(abs((start - end) // step))
    step = - step if start > end else step
    for _ in range(length):
        _seq.append(start)
        start += step
    return _seq

## 基本编程训练之二

1. 全部利用前面自编的函数产生计算 Pearson 相关系数的函数

    $$
    r_{X Y}=\frac{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)\left(y_{i}-\bar{y}\right)}{\sqrt{\sum_{i=1}^{n}\left(x_{i}-\bar{x}\right)^{2} \sum_{i=1}^{n}\left(y_{i}-\bar{y}\right)^{2}}}
    $$

    并计算-10 到 10 (比如间隔 0.5) 的序列 (可用自编函数 `seq()` 产生, 比如 $\mathrm{u}=\mathrm{seq}(-10,11)$), 求 $u$ 和 $u^{2}$ 的相关系数.

In [3]:
def corr(x, y):
    if len(x) != len(y):
        raise ValueError("x and y must have the same length")
    x_bar = sum(x) / len(x)
    y_bar = sum(y) / len(y)
    _corr = sum(map(lambda x, y: (x - x_bar) * (y - y_bar), x, y)) / \
        (sum([(xi - x_bar) ** 2 for xi in x]) *
         sum([(yi - y_bar) ** 2 for yi in y])) ** 0.5
    return _corr

In [4]:
u = seq(-10, 10.1, 0.5)
u2 = [i ** 2 for i in u]
corr(u, u2)

0.0

2. 编写类似于 `len()` 的函数求 `list`, `tuble`, `dict`, `str` 的长度.

In [5]:
def ilen(obj):
    if isinstance(obj, dict):
        obj = list(obj.items())
    _len = 0
    while True:
        try:
            obj[_len]
            _len += 1
        except IndexError:
            break
    return _len

In [6]:
ilen([1, 2, 3])

3

In [7]:
ilen((1, 2, 3))

3

In [8]:
ilen({'Name': 'Zara', 'Age': 7, 'Class': 'First'})

3

In [9]:
ilen("Hello World!")

12

3. 不用任何函数 (除了自编函数), 编写一个全部是某个数 (如 0, 1 或任何元素等) 的 $m\times n$ 矩阵或向量 (`list` 形式). 这里的所谓向量或矩阵是可直接以转换成 `np.array` 相应维数向量或矩阵的 `list`. 比如,
   
    ```python
    print(Const(7,2,3),'\n',Const(6,5))
    # [[7, 7, 7], [7, 7, 7]]
    # [6, 6, 6, 6, 6]
    ```

In [10]:
def const(num, m, n=1):
    if n == 1:
        matrix = [num] * m
    else:
        matrix = [[num] * n for i in range(m)]
    return matrix

In [11]:
print(np.array(const(7, 2, 3)))

[[7 7 7]
 [7 7 7]]


In [12]:
print(np.array(const(6, 5)))

[6 6 6 6 6]


4. 编写类似于 `R` 的 `diag()` 函数 (这里的矩阵和向量和前面一样是指可以直接用 `np.array` 转换成相应矩阵和向量的 `list`, 只允许用自编的及 `hasattr()` 函数, 结果示例:
    ```python
    print(np.array(Diag([3,3,1])),np.array(Diag(3)),np.array(Diag([[1,2,3,4],[9,8,7,6]])))
    # (array([[3, 0, 0],
    # [0, 3, 0],
    # [0, 0, 1]]),
    # array([[1, 0, 0],
    # [0, 1, 0],
    # [0, 0, 1]]),
    # array([1, 8]))
    ```

In [13]:
def diag(nums):
    matrix = []
    if isinstance(nums, list) and isinstance(nums[0], list):
        m = len(nums)
        n = len(nums[0])
        for i in range(min(m, n)):
            matrix.append(nums[i][i])
    else:
        if isinstance(nums, int):
            nums = [1] * nums
        n = len(nums)
        for i in range(n):
            row = [0] * (i) + [nums[i]] + [0] * (n-i-1)
            matrix.append(row)
    return matrix

In [14]:
print(np.array(diag([3, 3, 1])))

[[3 0 0]
 [0 3 0]
 [0 0 1]]


In [15]:
print(np.array(diag(3)))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [16]:
print(np.array(diag([[1, 2, 3, 4], [9, 8, 7, 6]])))

[1 8]


5. 不能用任何非允许函数 (可用自编函数), 得到某 `np.array` 矩阵(比如 `x=np.random.rand(3,2))` 的转置 (和 `x.T` 相同) 的函数.

In [17]:
def transorms(matrix):
    _transorms = []
    m, n = matrix.shape
    for j in range(n):
        row = []
        for i in range(m):
            row.append(matrix[i][j])
        _transorms.append(row)
    return _transorms

In [18]:
x = np.random.rand(3, 2)
print(x)
print(np.array(transorms(x)))

[[0.84429665 0.1543149 ]
 [0.83395225 0.43398287]
 [0.26198036 0.87704289]]
[[0.84429665 0.83395225 0.26198036]
 [0.1543149  0.43398287 0.87704289]]


6. 编写向量之间的外积类运算函数. 这一类运算是在两个 `np.array` 向量之间进行, 得到的是一个矩阵, 其行列数分别等于两个向量的长度, 而第 $ij$ 个元素为第一个向量的第 $i$ 个元素与第二个向量的第 $j$ 个元素计算而得. 请最多仅用自己编写的函数来写出实行这个运算的函数.

In [19]:
def outer_product(x, y):
    m = len(x)
    n = len(y)
    matrix = []
    for i in range(m):
        row = []
        for j in range(n):
            row.append(x[i]*y[j])
        matrix.append(row)
    return matrix

In [20]:
x = np.array([1, 2, 3])
y = np.array([1, 1, 1, 1])
print(np.array(outer_product(x, y)))

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]


7. 除了自己编写的函数及 `eval()` 函数, 不能用任何函数, 编写向量对矩阵行或列做各种运算, 包括四则运算、余、乘方、大于、小于等. 类似于 `R` 的 `sweep()` 函数.

In [21]:
def sweep(x, margin, stats, fun="-"):
    m = len(x)
    n = len(x[0])
    for i in range(m):
        for j in range(n):
            temp = stats[j] if margin == 1 else stats[i]
            x[i][j] = eval(str(x[i][j]) + fun + str(temp))
    return x

In [22]:
x = [[1, 3, 5, 7], [2, 4, 6, 8]]
print(np.array(x))
stats = [1, 1, 2, 2]
print(np.array(sweep(x, 1, stats)))

[[1 3 5 7]
 [2 4 6 8]]
[[0 2 3 5]
 [1 3 4 6]]


In [23]:
x = [[1, 3, 5, 7], [2, 4, 6, 8]]
print(np.array(x))
stats = [2, 1]
print(np.array(sweep(x, 2, stats, "+")))

[[1 3 5 7]
 [2 4 6 8]]
[[3 5 7 9]
 [3 5 7 9]]


8. 除了自己编写的函数, 不能用任何函数, 编写 `np.array` 矩阵乘积(试着产生 `x.dot(y.T)` 的结果)的函数.

In [24]:
def dot(x, y):
    m = len(x)
    n = len(y)
    p = len(y[0])
    matrix = [[0] * p for _ in range(m)]
    for i in range(m):
        for j in range(p):
            for k in range(n):
                matrix[i][j] = matrix[i][j] + x[i][k] * y[k][j]
    return matrix

In [25]:
x = np.random.rand(3, 4)
y = np.random.rand(5, 4)
print(np.array(dot(x, y.T)))

[[0.14963552 0.33004658 0.27666162 0.60789559 0.19080191]
 [0.76711433 0.95659815 0.76043472 1.36870115 1.34927651]
 [0.48317193 0.81274702 1.31606639 1.68673219 1.04562661]]


In [26]:
print(x.dot(y.T))

[[0.14963552 0.33004658 0.27666162 0.60789559 0.19080191]
 [0.76711433 0.95659815 0.76043472 1.36870115 1.34927651]
 [0.48317193 0.81274702 1.31606639 1.68673219 1.04562661]]


9. 求逆矩阵只允许使用前面自己编写的函数, 用主元 Gauss-Jordan (高斯-约当) 消元法求逆矩阵的函数.

In [27]:
def inverse(x):
    n = len(x)
    matrix = [[0] * 2 * n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            matrix[i][j] = x[i][j]
            if i == j:
                matrix[i][j+n] = 1
    for i in range(n):
        if matrix[i][i] == 0.0:
            # !TODO 该情况无法说明矩阵是奇异的
            raise ValueError("matrix is singular!")
        ratio = matrix[i][i]
        for k in range(2 * n):
            matrix[i][k] /= ratio
        for j in range(n):
            if i != j:
                ratio = matrix[j][i] / matrix[i][i]
                for k in range(2 * n):
                    matrix[j][k] -= ratio * matrix[i][k]
    for i in range(n):
        matrix[i] = matrix[i][n:]
    return matrix

In [28]:
x = np.array([[5, 4, 4], [8, 9, 8], [9, 4, 7]])

In [29]:
print(np.array(inverse(x)))

[[ 1.34782609 -0.52173913 -0.17391304]
 [ 0.69565217 -0.04347826 -0.34782609]
 [-2.13043478  0.69565217  0.56521739]]


In [30]:
print(np.linalg.inv(x))

[[ 1.34782609 -0.52173913 -0.17391304]
 [ 0.69565217 -0.04347826 -0.34782609]
 [-2.13043478  0.69565217  0.56521739]]


10. 写出一个函数 (只可以用自己编写的函数), 
    1.  把一个序列从小到大 (或从大到小) 排序 (类似于 `R` `sort()` 函数).
    2.  把相应于序列大小的下标找出来 (类似于 `R` `order()` 函数).

In [31]:
def partition(array, low, high, cmp):
    pivot = low - 1
    for i in range(low, high + 1):
        if cmp(array[i], array[high]):
            pivot += 1
            array[i], array[pivot] = array[pivot], array[i]
    return pivot


def _qsort(array, low, high, cmp):
    if low >= high:
        return
    pivot = partition(array, low, high, cmp)
    _qsort(array, low, pivot - 1, cmp)
    _qsort(array, pivot + 1, high, cmp)


def sort(array):
    def cmp_sort(a, b):
        return a <= b
    _qsort(array, 0, len(array) - 1, cmp_sort)
    return array


def order(array):
    def cmp_sort(a, b):
        return array[a] <= array[b]
    idxs = list(range(0, len(array)))
    _qsort(idxs, 0, len(array) - 1, cmp_sort)
    return idxs

In [32]:
sort([10, 9, 8, 7, 6, 5])

[5, 6, 7, 8, 9, 10]

In [33]:
order([10, 9, 8, 7, 6, 5])

[5, 4, 3, 2, 1, 0]